config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors
  # root "medical_centers#index"
  root "react#index"

  resources :medical_centers do
    resources :departments do
      resources :doctors do
        resources :visits do
          resources :inspection_reports
        end
      end
    end
    resources :patients
  end
  
  post '/search', to: 'search#search'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/visit.rb
class Visit < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
    has_many :inspection_reports, dependent: :destroy

    validates :datetime, :doctor_id, :patient_id, presence: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :find_medical_center, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_department, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_doctor, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_visit, only: [:show, :edit, :update, :destroy]
  before_action :authorize!

  def index
    redirect_to root_path unless @vp.index?
    @visits = @doctor.visits
  end

  def new
    redirect_to root_path unless @vp.index?
  end

  def create
    redirect_to root_path unless @vp.index?
    @visit = @doctor.visits.new(visit_params)

    if @visit.save
      VisitNotificationsMailer.with(doctor: @visit.doctor, patient: @visit.patient, visit: @visit).new_visit.deliver_later
      VisitNotifications::ReminderJob.perform_at(@visit.datetime - 1.day, @visit.id)
      VisitNotifications::ReminderJob.perform_at(@visit.datetime - 30.minutes, @visit.id)

      redirect_to medical_center_department_doctor_visits_path(@medical_center, @department, @doctor)
    else
      redirect_to :new
    end

  end

  def show
    redirect_to root_path unless @vp.index?
  end

  def edit
    redirect_to root_path unless @vp.index?
  end

  def update
    redirect_to root_path unless @vp.index?

    if @visit.update(visit_params)
      redirect_to medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, @visit)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path unless @vp.index?
    @visit.destroy
    redirect_to medical_center_department_doctor_visits_path(@medical_center, @department, @doctor)
  end

  private

  def authorize!
    @vp = VisitPolicy.new(current_user, @visit || Visit, @doctor)
  end

  def find_medical_center
    @medical_center = MedicalCenter.find(params[:medical_center_id])
  end

  def find_department
    @department = @medical_center.departments.find(params[:department_id])
  end

  def find_doctor
    @doctor = @department.doctors.find(params[:doctor_id])
  end

  def find_visit
    @visit = @doctor.visits.find(params[:id])
  end

  def visit_params
    params.require(:visit).permit(:datetime, :doctor_id, :patient_id)
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/index.html.erb
<h1>Visits</h1>

<ul>
  <% @visits.each do |visit| %>
    <li>
      <%= link_to "#{visit.datetime} - #{visit.patient.full_name}", medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, visit) %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to "Doctor #{@doctor.full_name}", medical_center_department_doctor_path(@medical_center, @department, @doctor) %>

app/views/visits/new.html.erb
<h1>New Visit</h1>
<%= form_with model: [@medical_center, @department, @doctor, @doctor.visits.build ], local: true do |form| %>
  <p>
    <%= form.label :datetime %><br>
    <%= form.datetime_field :datetime %>
  </p>

  <p>
    <%= form.label :patient %><br>
    <%= form.text_field :patient_id %>
  </p>

  <p>
    <%= form.label :doctor %><br>
    <%= form.text_field :doctor_id, value: @doctor.id, readonly: true %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>

<%= link_to "Doctor #{@doctor.full_name}", medical_center_department_doctor_path(@medical_center, @department, @doctor) %>

app/views/visits/show.html.erb
<h1><%= @visit.datetime%></h1>

<p><%= @visit.patient.full_name %></p>

<% if current_user.class.to_s == 'Admin' %>
 <ul>
    <li><%= link_to "Edit", edit_medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, @visit) %></li>
    <li><%= link_to "Destroy", medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, @visit),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></li>
  </ul><hr>
<% end %>

<%= link_to "Create Inspection Report", new_medical_center_department_doctor_visit_inspection_report_path(@medical_center, @department, @doctor, @visit) %>

<hr><%= link_to "Inspection Report Index", medical_center_department_doctor_visit_inspection_reports_path(@medical_center, @department, @doctor, @visit) %>

<hr><%= link_to "Visit Index #{@doctor.full_name}", medical_center_department_doctor_visits_path(@medical_center, @department, @doctor) %>