config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors
  # root "medical_centers#index"
  root "react#index"

  resources :medical_centers do
    resources :departments do
      resources :doctors do
        resources :visits do
          resources :inspection_reports
        end
      end
    end
    resources :patients
  end
  
  post '/search', to: 'search#search'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/inspection_report.rb
class InspectionReport < ApplicationRecord
  belongs_to :visit

  validates :medical_report, :medical_appointment, :visit_id, presence: true
end

app/controllers/inspection_reports_controller.rb
class InspectionReportsController < ApplicationController
  before_action :find_medical_center, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_department, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_doctor, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_visit, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :find_inspection_report, only: [:show, :edit, :update, :destroy]

  def index
    @inspection_reports = @visit.inspection_reports
  end

  def new; end

  def create
    @inspection_report = @visit.inspection_reports.create(inspection_report_params)
    report_path = medical_center_department_doctor_visit_inspection_report_url(@medical_center, @department, @doctor, @visit, @inspection_report)

    ReportNotificationsMailer.with(doctor: @doctor, patient: @visit.patient, report_path: report_path, visit: @visit).report_created.deliver_later

    redirect_to report_path
  end

  def show; end

  def edit; end

  def update
    if @inspection_report.update(inspection_report_params)
      report_path = medical_center_department_doctor_visit_inspection_report_url(@medical_center, @department, @doctor, @visit, @inspection_report)

      ReportNotificationsMailer.with(doctor: @doctor, patient: @visit.patient, report_path: report_path, visit: @visit).report_updated.deliver_later

      redirect_to report_path
    else
      render :edit
    end
  end

  def destroy
    @inspection_report.destroy
    redirect_to medical_center_department_doctor_visit_inspection_reports_path(@medical_center, @department, @doctor, @visit)
  end

  private

  def find_medical_center
    @medical_center = MedicalCenter.find(params[:medical_center_id])
  end

  def find_department
    @department = @medical_center.departments.find(params[:department_id])
  end

  def find_doctor
    @doctor = @department.doctors.find(params[:doctor_id])
  end

  def find_visit
    @visit = @doctor.visits.find(params[:visit_id])
  end

  def find_inspection_report
    @inspection_report = @visit.inspection_reports.find(params[:id])
  end

  def inspection_report_params
    params.require(:inspection_report).permit(:medical_report, :medical_appointment, :visit_id)
  end
end

app/helpers/inspection_reports_helper.rb
module InspectionReportsHelper
end

app/views/inspection_reports/edit.html.erb
<h1>Edit Visit</h1>

<%= form_with model: [@medical_center, @department, @doctor, @visit, @inspection_report], local: true do |form| %>
  <p>
    <%= form.label :medical_report %><br>
    <%= form.text_field :medical_report, value: @inspection_report.medical_report %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>

<%= link_to "Visit", medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, @visit) %>

app/views/inspection_reports/index.html.erb
<h1>Inspection Reports</h1>

<ul>
  <% @inspection_reports.each do |inspection_report| %>
    <li>
      <%= link_to "inspection_report - #{@visit.patient.full_name}", medical_center_department_doctor_visit_inspection_report_path(@medical_center, @department, @doctor, @visit, inspection_report) %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to "Visit", medical_center_department_doctor_visit_path(@medical_center, @department, @doctor, @visit) %>

app/views/inspection_reports/new.html.erb
<h1>New Inspection Report</h1>
<%= form_with model: [@medical_center, @department, @doctor, @visit, @visit.inspection_reports.build], local: true do |form| %>
  <p>
    <%= form.label :medical_report %><br>
    <%= form.text_field :medical_report %>
  </p>

  <p>
    <%= form.label :medical_appointment %><br>
    <%= form.text_field :medical_appointment %>
  </p>

  <p>
    <%= form.label :visit_id %><br>
    <%= form.text_field :visit_id, value: @visit.id, readonly: true %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>

<%= link_to "Inspection Report Index", medical_center_department_doctor_visit_inspection_reports_path(@medical_center, @department, @doctor, @visit) %>

app/views/inspection_reports/show.html.erb
<h1><%= @inspection_report.medical_report %></h1>

<p><%= @inspection_report.medical_appointment %></p>

<ul>
  <li><%= link_to "Edit", edit_medical_center_department_doctor_visit_inspection_report_path(@medical_center, @department, @doctor, @visit) %></li>
  <% if current_user.class.to_s == 'Admin' %>
    <li><%= link_to "Destroy", medical_center_department_doctor_visit_inspection_report_path(@medical_center, @department, @doctor, @visit),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<hr>

<%= link_to "Visit Index", medical_center_department_doctor_visits_path(@medical_center, @department, @doctor) %>