config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors
  # root "medical_centers#index"
  root "react#index"

  resources :medical_centers do
    resources :departments do
      resources :doctors do
        resources :visits do
          resources :inspection_reports
        end
      end
    end
    resources :patients
  end
  
  post '/search', to: 'search#search'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
  has_many :departments, dependent: :destroy
  has_many :patients, dependent: :destroy
  has_many :doctors, through: :departments

  validates :email, :address, :schedule, :legal_entity, presence: true
 end

app/controllers/medical_centers_controller.rb
class MedicalCentersController < ApplicationController
  before_action :find_medical_center, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, except: [:index]

  def index
    @medical_centers = MedicalCenter.all
    render json: @medical_centers
  end

  def new
    @medical_center = MedicalCenter.new
  end

  def create
    @medical_center = MedicalCenter.new(medical_center_params)
    if @medical_center.save
      render json: @medical_center
    else
      render json: @medical_center.errors
    end
  end

  def show; end

  def edit; end

  def update
    if @medical_center.update(medical_center_params)
      redirect_to @medical_center
    else
      render :edit
    end
  end

  def destroy
    @medical_center.destroy
    render json: { notice: 'medical center was successfully removed.' }
    # redirect_to root_path
  end

  private

  def authorize!
    authorize(@medical_center || MedicalCenter)
  end

  def find_medical_center
    @medical_center = MedicalCenter.find(params[:id])
  end

  def medical_center_params
    params.require(:medical_center).permit(:email, :address, :schedule, :legal_entity)
  end
end

app/helpers/medical_centers_helper.rb
module MedicalCentersHelper
end

app/views/medical_centers/_form.html.erb
<%= form_with model: medical_center, local: false do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <%= medical_center.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %><br>
    <%= medical_center.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :schedule %><br>
    <%= form.text_area :schedule %><br>
    <%= medical_center.errors.full_messages_for(:schedule).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :legal_entity %><br>
    <%= form.text_area :legal_entity %><br>
    <%= medical_center.errors.full_messages_for(:legal_entity).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_centers/edit.html.erb
<h1>Edit Medical Center</h1>

<%= render "form", medical_center: @medical_center %>

<hr>

<%= link_to "Medical Center  #{@medical_center.legal_entity}", medical_center_path(@medical_center) %>

app/views/medical_centers/index.html.erb
<h1>Medical Centers</h1>

<ul>
  <% @medical_centers.each do |medical_center| %>
      <% if current_user.class.to_s == 'Admin' %>
        <li><%= link_to medical_center.legal_entity, medical_center %></li>
      <% elsif current_user.department.medical_center == medical_center %>
        <li><%= link_to medical_center.legal_entity, medical_center %></li>
      <% end %>
  <% end %>
</ul>

<hr><%= link_to "New Medical Center", new_medical_center_path %>

app/views/medical_centers/new.html.erb
<h1>New Medical Center</h1>
<%= render "form", medical_center: @medical_center %>

<hr>

<%= link_to "Medical Center Index", medical_centers_path(@medical_center) %>

app/views/medical_centers/show.html.erb
<h1><%= @medical_center.legal_entity %></h1>

<p><%= @medical_center.email %></p>
<p><%= @medical_center.address %></p>
<p><%= @medical_center.schedule %></p>

<hr>
<% if current_user.class.to_s == 'Admin' %>
  <ul>
    <li><%= link_to "Edit", edit_medical_center_path(@medical_center) %></li>
    <li><%= link_to "Destroy", medical_center_path(@medical_center),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></li>
    <li><%= link_to "Create Department", new_medical_center_department_path(@medical_center) %></li>
  </ul><hr>
<% end %>

<h2>Departments</h2>
<ul>
  <% @medical_center.departments.each do |department| %>
    <% if current_user.class.to_s == 'Admin' %>
      <li><%= link_to department.name, medical_center_department_path(@medical_center, department) %></li>
    <% elsif current_user.department == department %>
      <li><%= link_to department.name, medical_center_department_path(@medical_center, department) %></li>
    <% else %>
      <li><%= link_to_if false, department.name, medical_center_department_path(@medical_center, department) %></li>
    <% end %>
  <% end %>
</ul>
<hr><li><%= link_to "Patient Index", medical_center_patients_path(@medical_center) %></li>
<hr><%= link_to "Medical Center Index", root_path %>