config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :doctors
  # root "medical_centers#index"
  root "react#index"

  resources :medical_centers do
    resources :departments do
      resources :doctors do
        resources :visits do
          resources :inspection_reports
        end
      end
    end
    resources :patients
  end
  
  post '/search', to: 'search#search'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :department
  has_many :visits, dependent: :destroy

  validates :full_name, :phone_number, :email, :department_id, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_medical_center, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  before_action :find_department, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  before_action :find_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authorize!
  
  def index
    redirect_to root_path unless @dp.index?
    @doctors = @department.doctors
  end

  def new
    redirect_to root_path unless @dp.create?
  end

  def create
    redirect_to root_path unless @dp.create?
    @doctor = @department.doctors.new(doctor_params)   
    
    if @doctor.save
      redirect_to medical_center_department_doctor_path(@medical_center, @department, @doctor)
    else
      render :new
    end
  end

  def show
    redirect_to root_path unless @dp.show?
  end

  def edit
    redirect_to root_path unless @dp.update?
  end

  def update
    redirect_to root_path unless @dp.update?

    if @doctor.update(doctor_params)
      redirect_to medical_center_department_doctor_path(@medical_center, @department, @doctor)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path unless @dp.destroy?

    @doctor.destroy
    redirect_to medical_center_department_doctors_path(@medical_center, @department)
  end

  private

  def authorize!
    @dp = DoctorPolicy.new(current_user, @doctor || Doctor, @department)
  end

  def find_medical_center
    @medical_center = MedicalCenter.find(params[:medical_center_id])
  end

  def find_department
    @department = @medical_center.departments.find(params[:department_id])
  end

  def find_doctor
    @doctor = @department.doctors.find(params[:id])
  end
  
  def doctor_params
    params.require(:doctor).permit(:full_name, :phone_number, :email, :department_id, :password)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= form_with model: [@medical_center, @department, @doctor], local: true do |form| %>
  <p>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name, value: @doctor.full_name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_area :email, value: @doctor.email  %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_area :phone_number, value: @doctor.phone_number  %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>

<%= link_to "Doctor #{@doctor.full_name}", medical_center_department_doctor_path(@medical_center, @department, @doctor) %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>


<ul>
  <% @doctors.each do |doctor| %>
    <% if current_user.class.to_s == 'Admin' %>
      <li><%= link_to doctor.full_name, medical_center_department_doctor_path(@medical_center, @department, doctor) %></li>
    <% elsif current_user == doctor %>
      <li><%= link_to doctor.full_name, medical_center_department_doctor_path(@medical_center, @department, doctor) %></li>
    <% else %>
      <li><%= link_to_if false, doctor.full_name, medical_center_department_doctor_path(@medical_center, @department, doctor) %></li>
    <% end %>
  <% end %>
</ul>

<hr><%= link_to "Departament #{@department.name}", medical_center_department_path(@medical_center, @department) %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>
<%= form_with model: [@medical_center, @department, @department.doctors.build ], local: true do |form| %>
  <p>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password, value: '123321', readonly: true %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<hr>

<%= link_to "Departament #{@department.name}", medical_center_department_path(@medical_center, @department) %>

app/views/doctors/show.html.erb
<h1><%= @doctor.full_name%></h1>

<p><%= @doctor.email %></p>
<p><%= @doctor.phone_number %></p>

<% if current_user.class.to_s == 'Admin' %>
 <ul>
    <li><%= link_to "Edit", edit_medical_center_department_doctor_path(@medical_center, @department, @doctor) %></li>
    <li><%= link_to "Destroy", medical_center_department_doctor_path(@medical_center, @department, @doctor),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></li>
  </ul><hr>
<% end %>

<hr><%= link_to "All #{@doctor.full_name} visits", medical_center_department_doctor_visits_path(@medical_center, @department, @doctor) %>

<hr><%= link_to "Create Visit", new_medical_center_department_doctor_visit_path(@medical_center, @department, @doctor) %>

<hr><%= link_to "Doctor Index #{@department.name}", medical_center_department_doctors_path(@medical_center, @department) %>